spring.application.name=IOBANK
server.port=8080

Spring.dataSource.url=jdbc:mysql://localhost:3306/
spring.dataSource.username=root
spring.dataSource.password=bangbang@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
