spring.application.name=IOBANK
server.port=8080

Spring.dataSource.url=jdbc:mysql://localhost:3306/bank_db
spring.dataSource.username=root
spring.dataSource.password=bangbang@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#Security Configuration
jwtSecret=${jwtSecret:78835b50e86fe2b0ff5209faf397e930c703c36a179e469f8d76aa422f83576e}